name: Deploy Static Website

on:
  workflow_dispatch:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/builder:latest
      volumes:
      - /github/workspace:/srv/jekyll
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make Gemfile.lock Writeable
      run: chmod a+w Gemfile.lock
    - name: Build
      run: |
        jekyll build --future
    - name: Store Website
      uses: actions/upload-artifact@v2
      with:
        name: my-site
        path: _site/

  deploy-to-azure:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get Website
      uses: actions/download-artifact@v2
      with:
        name: my-site
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload Files
      uses: azure/CLI@v1
      env:
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob sync -s . -c '$web' --account-name "$STORAGE_ACCOUNT_NAME"
    - name: Set Cache Control
      uses: azure/CLI@v1
      env:
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob list -c '$web' --account-name "$STORAGE_ACCOUNT_NAME" -o table | grep -e .png -e .jpg -e .ico | awk '{ print $1 }' | xargs -i az storage blob update -c '$web' --account-name "$STORAGE_ACCOUNT_NAME" -n "{}" --content-cache-control 'max-age=2592000'
          az storage blob list -c '$web' --account-name "$STORAGE_ACCOUNT_NAME" -o table | grep -e .js -e .css | awk '{ print $1 }' | xargs -i az storage blob update -c '$web' --account-name "$STORAGE_ACCOUNT_NAME" -n "{}" --content-cache-control 'max-age=691200'
          az storage blob list -c '$web' --account-name "$STORAGE_ACCOUNT_NAME" -o table | grep .xml | awk '{ print $1 }' | xargs -i az storage blob update -c '$web' --account-name "$STORAGE_ACCOUNT_NAME" -n "{}" --content-cache-control 'max-age=86400'
